### ISSUE TITLE
The WebView can't load the html file under assets directory

### ISSUE THREAD

**Issue by codediving** [googlearchive/chromium-webview-samples#1]
I import project 'jsinterface-example' from zips and run it on Eclipse IDE. To be sad for me that it do not display as I think.
![display](https://f.cloud.github.com/assets/5959179/1839201/18bb4848-7474-11e3-9126-f838b18d0a52.png)
When I debug it, the result is as followd:
![debug](https://f.cloud.github.com/assets/5959179/1839210/5d0c32f0-7474-11e3-9bd3-b06f4b3c81be.png)
But when it put the 'index.html' to assets directly, and replace 'return "file:///android_asset/www/index.html#"+hash;'  with 'return "file:///android_asset/index.html#"+hash;' it display like :
![changed](https://f.cloud.github.com/assets/5959179/1839236/e397c046-7474-11e3-8b60-45b558c0b089.png)
Why?? Is that the WebView can't load file under deeper directory under asserts from KitKat?

My operator system is window7 and the android emulator is version 2.0.1 and the virtual devices  Nexus S-4.1.1-API16-480x800 and
 <uses-sdk
        android:minSdkVersion="8"
        android:targetSdkVersion="19" />

**Comment by gauntface** [comment]
Looks like a bug on my part somewhere. Will take a look over the weekend or Monday at the latest :)

**Comment by gauntface** [comment]
Apologies. This was an issue with git where I hadn't committed the modernizer file I needed.

FYI Going to Chrome://inspect on my desktop with the device connected and inspecting the webview's console helped show what the problem :)

Thanks for pointing it out
