### ISSUE TITLE
Cordova 6.2.3 has no WebChromeClient,how can i override the onJsPrompt()?

### ISSUE THREAD

**Issue by coldJune** [googlearchive/chromium-webview-samples#10]
when I update my project from cordova 3 to cordova 6,I find there is no WebChromeClient,but my project used this Class and override the onJsPrompt().
Now,how should i do base on Cordova 6  to override OnJsPrompt() 
`package com.qtby.gxwlc;

import org.apache.cordova.CordovaChromeClient;
import org.apache.cordova.CordovaInterface;
import org.apache.cordova.CordovaWebView;

import com.jsdemo.ClientTool;
import com.jsdemo.JsNativeFunc;

import android.content.Intent;
import android.webkit.JsPromptResult;
import android.webkit.WebView;

public class CustomerWebChromeClient extends CordovaChromeClient {

	public CustomerWebChromeClient(CordovaInterface ctx, CordovaWebView app){
		super(ctx, app);
	}
	
	JsNativeFunc jsNativeFunc;
	
	public JsNativeFunc getJsNativeFunc(){
		return jsNativeFunc;
	}
	
	public boolean isJsNativeFunc(int requestCode){
		if(jsNativeFunc == null)
			return false;
		return jsNativeFunc.isJsNativeFunc(requestCode);
	}
	
	public void jsResult(int requestCode, int resultCode,
    		Intent intent){
		jsNativeFunc.jsResult(requestCode, resultCode, intent);
	}
	
	
	@Override
	public boolean onJsPrompt(WebView view, String origin, String message,
			String defaultValue, JsPromptResult result) {
		if(ClientTool.callNativeFunc(message)){
			this.jsNativeFunc = new JsNativeFunc(cordova, appView, result);
			String method = ClientTool.getCallMethod(message);
			if("AUDIO".equalsIgnoreCase(method)){/*录音*/
				jsNativeFunc.audio();
			}else if("TELPHONE".equalsIgnoreCase(method)){/*手机号*/
				result.confirm(jsNativeFunc.getUserPhone());
			}else if("CAMERA".equalsIgnoreCase(method)){ /*相机*/
				jsNativeFunc.camera();
			}else if("PICTURE".equalsIgnoreCase(method)){/*相册*/
				jsNativeFunc.picture();
			}else if("HIDE".equalsIgnoreCase(method)){
				result.confirm("");
				//this.appView.loadUrl("javascript:window.close();");
//				cordova.getActivity().finish();
				cordova.getActivity().moveTaskToBack(true);
			}else if("GOBACK".equalsIgnoreCase(method)){
				result.confirm("");
				//this.appView.loadUrl("javascript:window.close();");
				cordova.getActivity().finish();
			}/*else if("URL".equalsIgnoreCase(method)){
				String operID = "sgddxt";
				String operSrc = "sgddxt";
				Long argutsname = System.currentTimeMillis();
		        String key = "sc028abcdefghijklm";
		        String hashCode = "";
				try {
					hashCode = encoderByMd5(operID+argutsname+key);
				} catch (NoSuchAlgorithmException e) {
				} catch (UnsupportedEncodingException e) {
				}
		        String _url = "...";
				result.confirm(_url);
			}*/else{
				return super.onJsPrompt(view, origin, message, defaultValue, result);
			}
			return true;
		}
		return super.onJsPrompt(view, origin, message, defaultValue, result);
	}

}
`

**Comment by andrewvmail** [comment]
You do this now.
```import org.apache.cordova.engine.SystemWebChromeClient;```

```extends SystemWebChromeClient```

https://github.com/apache/cordova-android/blob/master/framework/src/org/apache/cordova/engine/SystemWebChromeClient.java

Cheers
