### ISSUE TITLE
Is this supposed to work on Android 4.4 ?

### ISSUE THREAD

**Issue by oldergod** [googlearchive/chromium-webview-samples#6]
The generated manifest `uses-sdk` is as follow

``` xml
<uses-sdk android:minSdkVersion="19" android:targetSdkVersion="21" />
```

But L starts at 21. Why do we have a minSdkVersion to 19 ?

**Comment by osrl** [comment]
This or any other file upload solution DOES NOT WORK WITH KITKAT (19)
